server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yuyone47!
    url: jdbc:mysql://localhost:3306/mybook?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&useUnicode=true&serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    #关闭mybatis-plus的自动驼峰命名
    map-underscore-to-camel-case: false
    #日志输出详细化，mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
